version: '3'
services:
  chrome-remote-desktop:
    image: epicmineryoutube/chrome-remote-desktop-epicminer
    environment:
      - CODE=4/0AanRRrto8KJLguWst4bUbfzH9JtnB1q2N8MSuWjgNrqZAtpj0JQXc_MgaE3y1Vcdb1DMIw
      - PIN=912286
      - HOSTNAME=KING-QUEEN66
